FROM maven:3.5-jdk-8-alpine as build
COPY src /home/app/src
COPY devices.json /home/app/
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:8-jre-alpine
COPY --from=build /home/app/devices.json /usr/local/lib/
COPY --from=build /home/app/target/recruitment-test-1.0.jar /usr/local/lib/recruitment-test-1.0.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=production","/usr/local/lib/recruitment-test-1.0.jar"]